<a href="https://colab.research.google.com/github/marimiya/hello-world/blob/master/Copy_of_PyCUDA_intro.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Part 1**
First of all you need to check whether you have a GPU-accelerated Runtime. To do this, Select the 'Runtime' menu and then choose 'Change runtime type'. You should then choose 'GPU' if it is not already selected. Once done, you may need to select the 'Connect' option at the top right of your notebook window. 
When it has loaded and connected you should run the following command to check whether the system is indeed using a GPU:

In [0]:
!nvidia-smi

Thu Oct 24 02:14:37 2019       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 430.50       Driver Version: 418.67       CUDA Version: 10.1     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  Tesla K80           Off  | 00000000:00:04.0 Off |                    0 |
| N/A   55C    P8    28W / 149W |      0MiB / 11441MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU  

If all is well, you should see some output that includes the type of GPU being used (k80) and lists any processed running (none for the moment).

Next, we need to install PyCUDA:

In [0]:
pip install pycuda

     |████████████████████████████████| 1.6MB 3.5MB/s 
     |████████████████████████████████| 61kB 8.2MB/s 
     |████████████████████████████████| 471kB 43.1MB/s 
  Created wheel for pycuda: filename=pycuda-2019.1.2-cp36-cp36m-linux_x86_64.whl size=4536167 sha256=d9bad67d3a97ed3dacf8f04ca196d3daf26b6877eeea0a1f47e3ed46c2141588
  Stored in directory: /root/.cache/pip/wheels/a6/60/f0/b1c430c73d281ac3e46070480db50f7907364eb6f6d3188396
  Created wheel for pytools: filename=pytools-2019.1.1-py2.py3-none-any.whl size=58424 sha256=37bba396e1ba6f5c98623e764a12618d4e678e02aa02258d0487996505142b84
  Stored in directory: /root/.cache/pip/wheels/83/df/0b/75ac4572aaa93e3eba6a58472635d0fda907f5f4cf884a3a0c
  Created wheel for mako: filename=Mako-1.1.0-cp36-none-any.whl size=75363 sha256=2d96c964db01ede64e6dfb827f4c29628364e6c965488927bf1cf065b27f554c
  Stored in directory: /root/.cache/pip/wheels/98/32/7b/a291926643fc1d1e02593e0d9e247c5a866a366b8343b7aa27
Successfully built pycuda pytools mako


Now we should be able to import the PyCUDA libraries that we need:

In [0]:
import pycuda.driver as cuda
import pycuda.autoinit
from pycuda.compiler import SourceModule

We will be using numpy quite a lot so let's import that right away:

In [0]:
import numpy as np

Okay, let's create a 4 x 4 array using numpy's random function and show the contents.

In [0]:
a = np.random.randn(4,4)
a

array([[-0.64958587,  0.24983324, -0.89895253, -0.801612  ],
       [ 0.30447968, -2.07722494,  1.35775999, -2.04195412],
       [-0.65881711,  0.88978129, -0.2129629 ,  2.63858029],
       [ 0.70924416,  0.45147205,  0.60061799, -0.02043707]])

Let's check the type of one of the elements:

In [0]:
type(a[0,0])

numpy.float64

As you should see, this is of type float64. This is not always the right data type for kernel functions for the following reasons:
Only Enterprise GPUs (i.e. Volta/Pascal rather than GeForce/RTX) tend to support Full Precision (float64). Even then, they tend to have better support for lower precision (e.g. int32, fp16 etc.)
So it's better to either specify the type or cast it before passing it to the GPU:

In [0]:
b = np.random.randn(4,4)
b = b.astype(np.float32)
print(b)
print(type(b[0,0]))
print("")
c = np.random.randint(low=1, high=100, size=16, dtype=np.int16).reshape(4,4)
print(c)
print(type(c[0,0]))


[[-1.9560276  -0.19318388 -1.3799247  -0.23417418]
 [ 0.449587    0.8313106   2.4740198  -1.293046  ]
 [ 0.44903103  1.6990381  -0.845149   -0.5263452 ]
 [-0.6007457   1.3219384  -0.6088996  -0.35990486]]
<class 'numpy.float32'>

[[34 62 19 84]
 [48 97 59 60]
 [25 29 66 17]
 [53 45  2 17]]
<class 'numpy.int16'>


Okay, now let's take a look at the way our data can be transferred over to the device (GPU) for a kernel to act upon.
In this example, we use the cuda.mem_alloc to allocate some gpu memory. In order to do this, we need to determine how much memory we need. For this we use the nbytes property of our variable.


In [0]:
b_gpu = cuda.mem_alloc(b.nbytes)
print(str(b.nbytes) + " bytes allocated")

64 bytes allocated


That has allocated the memory, so now we can transfer the data to the gpu memory (htod = host to device):

In [0]:
cuda.memcpy_htod(b_gpu, b)

Next we need to create some code to execute on the GPU - our kernel function - that will operate on the data we just passed.

In this case all we are going to do is multiply the contents of the a matrix by 2.

In [0]:
mod = SourceModule("""
  __global__ void doublify(float *a)
  {
    int idx = threadIdx.x + threadIdx.y*4;
    a[idx] *= 2;
  }
  """)

If there were no errors then our kernel has compiled and is ready to be called.

In [0]:
func = mod.get_function("doublify")
func(b_gpu, block=(4,4,1))

Let's just take a look at what we just executed.
First we got a handle to the doublify function that we just created, then we called the function passing a_gpu as the function argument and we specified the launch configuration using the block parameter - more on this shortly.


In [0]:
b_doubled = np.empty_like(b)
cuda.memcpy_dtoh(b_doubled, b_gpu)
print(b_doubled)
print(b)

Okay, so that worked (hopefully) but what did the kernel code actually do? 
To more fully understand this we need to take a look at the way that kernels are launched (Slides will be presented).

**Part 2**

To better understand what is going on when you launch a kernel let's try a few experiments.

We'll create a simple kernel that just sets the elements of the input array to the thread index. This should help show what is going on


In [0]:
mod2 = SourceModule("""
  __global__ void getInfo(int *a)
  {
    int idx = threadIdx.x;
    a[idx] = threadIdx.x;

  }
  """)

In [0]:
# Create an empty 1d array
d = np.zeros((16), dtype=np.uint32)
# Allocate GPU memory
d_gpu = cuda.mem_alloc(d.nbytes)
# clear the gpu memory
cuda.memcpy_htod(d_gpu, d)

# Get the function handle
func2 = mod2.get_function("getInfo")
# Create a lauch configuration with 4 threads and 1 block
func2(d_gpu, block=(4,1,1))

# Create array for output
d_out = np.empty_like(d)
# Copy the gpu memory to the host
cuda.memcpy_dtoh(d_out, d_gpu)

# Print data out
print(d_out)

# Free up the memory
d_gpu.free()

[0 1 2 3 0 0 0 0 0 0 0 0 0 0 0 0]


Do you understand what the output has produced? 
Our kernel has launched a block with 4 threads (block = (4,1,1) means that 4 threads are created in the block on the x dimension, with no additional threads on the y or z dimensions). Each thread has written its threadIdx.x value into the array element corresponding to this value. Since there are only 4 threads, only the first 4 elements have been updated.
If we want to write into the other elements we will have to do one of several things:

*   Increase the number of threads in the block
*   Increase the number of blocks
*   Iterate within the kernel

Let's try these one by one.

By changing the number of threads per block to 16 (in the x dimension) we can fully populate the array.

In [0]:
# Allocate GPU memory
d_gpu = cuda.mem_alloc(d.nbytes)
# clear the gpu memory
cuda.memcpy_htod(d_gpu, d)

# Create a lauch configuration with 416 threads
func2(d_gpu, block=(16,1,1))

# Copy the gpu memory to the host
cuda.memcpy_dtoh(d_out, d_gpu)

# Present data as a matrix
print(d_out)

# Free gpu memory
d_gpu.free()

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]


In order to make increasing the number of blocks effective we will need to change the kernel so that it can use them. Without doing this each block will simply write into the same array element as the others. By adding the blockIdx.x into the kernel we can use it to map each thread and block to a specific element.

In [0]:
mod3 = SourceModule("""
  __global__ void getInfo(int *a)
  {
    int idx = threadIdx.x + blockIdx.x * blockDim.x;
    a[idx] = idx;

  }
  """)

In [0]:
# Allocate GPU memory
d_gpu = cuda.mem_alloc(d.nbytes)
# clear the gpu memory
cuda.memcpy_htod(d_gpu, d)

# Get the function handle
func3 = mod3.get_function("getInfo")
# Create a lauch configuration with 4 threads and 4 blocks
func3(d_gpu, block=(4,1,1), grid=(4,1,1))

# Copy the gpu memory to the host
cuda.memcpy_dtoh(d_out, d_gpu)

# Present data as a matrix
print(d_out)

# Free gpu memory
d_gpu.free()

Lets try some iteration within the kernel next. This is only really used when the size of the problem exceeds the total number of threads available on the gpu but, for the sake of illustration we'll try it here.

In [0]:
mod4 = SourceModule("""
  __global__ void getInfo(int *a)
  {
    int idx = threadIdx.x;
    for (int i=0;i<16;i+=4)
    {
      a[idx + i] = idx + i;
    }
  }
  """)

In [0]:
# Allocate GPU memory
d_gpu = cuda.mem_alloc(d.nbytes)
# clear the gpu memory
cuda.memcpy_htod(d_gpu, d)

# Get the function handle
func3 = mod4.get_function("getInfo")
# Create a lauch configuration with 4 threads and 4 blocks
func3(d_gpu, block=(4,1,1))

# Copy the gpu memory to the host
cuda.memcpy_dtoh(d_out, d_gpu)

# Present data as a matrix
print(d_out)

# Free gpu memory
d_gpu.free()

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]


Okay, so as a final exercise, let's see if the following makes sense. Note that we are using a 3D matrix as input this time. However, as far as the C-based kernel is concerned, there is no difference between a 3D array and a 1D array - ultimately they are both just contiguous memory.
Check that you understand the output. 

In [0]:
mod5 = SourceModule("""
  __global__ void getInfo(int *a)
  {
    int idx = 4 * (blockIdx.x * blockDim.x + threadIdx.x);
    a[idx] = threadIdx.x;
    a[idx + 1] = blockIdx.x;
    a[idx + 2] = blockDim.x;
    a[idx + 3] = gridDim.x;
  }
  """)

In [0]:
# Create an empty 3d array
b = np.zeros((4,4,4), dtype=np.uint32)
# Allocate GPU memory
b_gpu = cuda.mem_alloc(b.nbytes)

# Get the function handle
func = mod5.get_function("getInfo")
# Create a lauch configuration with 4 threads and 4 blocks
func(b_gpu, block=(4,1,1), grid=(4,1,1))

# Create array for output
b_out = np.empty_like(b)
# Copy the gpu memory to the host
cuda.memcpy_dtoh(b_out, b_gpu)

# Present data as a matrix
print(b_out.reshape((4,4,4)))


Try changing some of the parameters such as block size and see what happens

Finally, see if you can use what you have learned to create kernel that multiplies the elements in matrix a by matrix b. The outline has been provided. Please see if you can complete the code and produce a correct result!
The assertion will fail if you don't. Remember to edit the launch configuration.

In [0]:
mmult = SourceModule("""
  __global__ void multiply(int *a, int *b)
  {
    int idx = TODO;
    // multiply each element of a by b 
    // TODO
  }
  """)

a = np.array([[1,2,3,4],[1,2,3,4],[1,2,3,4],[1,2,3,4]],dtype=np.uint32)
b = np.array([[1,1,1,1],[2,2,2,2],[3,3,3,3],[4,4,4,4]],dtype=np.uint32)

# Allocate GPU memory
a_gpu = cuda.mem_alloc(a.nbytes)
b_gpu = cuda.mem_alloc(b.nbytes)
# set the gpu memory
cuda.memcpy_htod(a_gpu, a)
cuda.memcpy_htod(b_gpu, b)

# Get the function handle
func = mmult.get_function("multiply")
# Create a lauch configuration with 4 threads and 1 block
func(a_gpu, b_gpu, TODO ......)

# Create array for output
a_out = np.empty_like(a)
# Copy the gpu memory to the host
cuda.memcpy_dtoh(a_out, a_gpu)

# Print data out
print(a_out)

# Free up the memory
a_gpu.free()
b_gpu.free()

assert (a_out == [[1,2,3,4],[2,4,6,8],[3,6,9,12],[4,8,12,16]]).all()


There is a simpler way of handling arrays than what we have so far looked at. The GPUArray is an abstraction that removes some of the steps. It is useful to understand what those steps did though, because it helps your understanding of what is going on, which is helpful when it comes to getting the best performance from your code.

In [0]:
from pycuda import gpuarray

x = np.random.randn(5).astype(np.float32)
x_gpu = gpuarray.to_gpu(x)

x_gpu

array([-0.99748343, -0.54913306, -0.15226158,  0.47780636,  0.44367114],
      dtype=float32)

You can operate directly on gpuarrays as if they were normal numpy arrays.


In [0]:
x_gpu = x_gpu * 3
x_gpu

array([-2.9924502 , -1.6473992 , -0.45678475,  1.4334191 ,  1.3310134 ],
      dtype=float32)

GPUArrays also support slicing. The one thing that you cannot do is indexing though:

In [0]:
x_gpu[:3]

x_gpu[3]

array(1.4334191, dtype=float32)

In order to use a GPUArray in a function created with SourceModule (as per the examples above) we need to use the **gpudata** attribute:

In [0]:
 func = mod.get_function("doublify")
 func(x_gpu.gpudata, block = (5,1,1))

 x_gpu

array([-5.9849005, -3.2947984, -0.9135695,  2.8668382,  2.662027 ],
      dtype=float32)

As you can see, this is much cleaner than the previous method! 

Next we need to explain a couple of important concepts that, so far, we ignored.
First of all, you may have noticed that the kernel function we declared was preceeded by the \_\_global\_\_ keyword. This tells the compiler that this is kernel (i.e. it will be called from the CPU but executed on the GPU). You will also have seen that the return type was 'void'. This is because kernel function cannot return values. Instead, any results need to be handled by passing in a pointer to a variable and manipulating the data within the kernel.

Additionally, sometimes you need to call a function from within your kernel. This can be done by declaring a \_\_device\_\_ function, which will reside only on the GPU.

Let's create a simple example of a device function:


In [0]:
dev = SourceModule("""
__device__ int times2( float px); // declaration
  __global__ void  matAdd(float *a)  
{  
        int idx = blockIdx.x*blockDim.x+threadIdx.x;  
        
        a[idx] = times2(idx);   

}  
  __device__ int times2( float idx) // implementation
{
    return idx * 2; 
}  
""")

func = dev.get_function("matAdd")
func(x_gpu.gpudata, block = (5,1,1))

x_gpu

array([0., 2., 4., 6., 8.], dtype=float32)

Okay, next see if you can create your own matrix multiplication kernel. Remember that there is a reduction operation in a matrix multiplication that needs to be run after the multiplication, so watch out for data races!

In [0]:
# Create your kernel here

mod_mari = SourceModule("""
  __global__ void doublify(float *a)
  {
    int idx = threadIdx.x + threadIdx.y*4;
    a[idx] *= 3;
  }
  """)

func = mod_mari.get_function("doublify")
func(b_gpu, block=(4,4,1))

b_doubled = np.empty_like(b)
cuda.memcpy_dtoh(b_doubled, b_gpu)
print(b_doubled)
print(b)


[[-46.944664  -4.636413 -33.11819   -5.62018 ]
 [ 10.790088  19.951454  59.376472 -31.033104]
 [ 10.776745  40.776917 -20.283575 -12.632284]
 [-14.417896  31.72652  -14.61359   -8.637716]]
[[-1.9560276  -0.19318388 -1.3799247  -0.23417418]
 [ 0.449587    0.8313106   2.4740198  -1.293046  ]
 [ 0.44903103  1.6990381  -0.845149   -0.5263452 ]
 [-0.6007457   1.3219384  -0.6088996  -0.35990486]]


In [0]:
mod2_mari = SourceModule("""
  __global__ void getInfo(int *a)
  {
    int idx = threadIdx.x;
    a[idx] = threadIdx.x;

  }
  """)

# Create an empty 1d array
d = np.zeros((16), dtype=np.uint32)
print(d)
# Allocate GPU memory
d_gpu = cuda.mem_alloc(d.nbytes)
# clear the gpu memory
cuda.memcpy_htod(d_gpu, d)

# Get the function handle
func2 = mod2_mari.get_function("getInfo")
# Create a lauch configuration with 4 threads and 1 block
func2(d_gpu, block=(4,1,1))

# Create array for output
d_out = np.empty_like(d)
# Copy the gpu memory to the host
cuda.memcpy_dtoh(d_out, d_gpu)

# Print data out
print(d_out)

# Free up the memory
d_gpu.free()


[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 1 2 3 0 0 0 0 0 0 0 0 0 0 0 0]


In [0]:
mod3_mari = SourceModule("""
  __global__ void getInfo(int *a)
  {
    int idx = threadIdx.x + blockIdx.x * blockDim.x;
    a[idx] = idx;

  }
  """)


# Allocate GPU memory
d_gpu = cuda.mem_alloc(d.nbytes)
# clear the gpu memory
cuda.memcpy_htod(d_gpu, d)

# Get the function handle
func3 = mod3_mari.get_function("getInfo")
# Create a lauch configuration with 4 threads and 4 blocks
func3(d_gpu, block=(4,1,1), grid=(4,1,1))

# Copy the gpu memory to the host
cuda.memcpy_dtoh(d_out, d_gpu)

# Present data as a matrix
print(d_out)

# Free gpu memory
d_gpu.free()

In [0]:
mod3_mari = SourceModule("""
  __global__ void getInfo(int *a)
  {
    int idx = threadIdx.x + blockIdx.x * blockDim.x;
    a[idx] = idx;

  }
  """)

In [3]:
b = np.zeros((4,4,4), dtype=np.uint32)
print(b)

[[[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]

 [[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]

 [[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]

 [[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]]


In [0]:
# Create your 
calling code here

Well done (or cmomiserations)!

You have completed the introduction.